// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDgPVoolWlMStAv3FLj7yoTSZ2KtUXiHY',
    appId: '1:933736868776:web:eaf72419d64d026c35cb9d',
    messagingSenderId: '933736868776',
    projectId: 'pbshop-e97ac',
    authDomain: 'pbshop-e97ac.firebaseapp.com',
    storageBucket: 'pbshop-e97ac.firebasestorage.app',
    measurementId: 'G-QNE7NS3FC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobzXYA3VYuAN1QRW-ftQ1ximxaWRb5HU',
    appId: '1:933736868776:android:40cfeabb3a3448df35cb9d',
    messagingSenderId: '933736868776',
    projectId: 'pbshop-e97ac',
    storageBucket: 'pbshop-e97ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbBlrEyMcou0RpivKZoCMnhcSckz_OAVM',
    appId: '1:933736868776:ios:65a3ec99a2ef27b135cb9d',
    messagingSenderId: '933736868776',
    projectId: 'pbshop-e97ac',
    storageBucket: 'pbshop-e97ac.firebasestorage.app',
    iosBundleId: 'com.example.pbshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbBlrEyMcou0RpivKZoCMnhcSckz_OAVM',
    appId: '1:933736868776:ios:65a3ec99a2ef27b135cb9d',
    messagingSenderId: '933736868776',
    projectId: 'pbshop-e97ac',
    storageBucket: 'pbshop-e97ac.firebasestorage.app',
    iosBundleId: 'com.example.pbshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDgPVoolWlMStAv3FLj7yoTSZ2KtUXiHY',
    appId: '1:933736868776:web:f71f43613db3c51f35cb9d',
    messagingSenderId: '933736868776',
    projectId: 'pbshop-e97ac',
    authDomain: 'pbshop-e97ac.firebaseapp.com',
    storageBucket: 'pbshop-e97ac.firebasestorage.app',
    measurementId: 'G-17BSZ4E481',
  );
}
